-- SCRIPT DE MIGRACIÓN: MEJORA DE AUDITORÍA (v1.7.0)
-- Ejecutar en el esquema GESAP

ALTER TABLE GESAP.RECORDATORIO_ENVIO_LOGS ADD (
    HTTP_METHOD    VARCHAR2(10),
    USER_AGENT     CLOB,
    CORRELATION_ID VARCHAR2(50),
    RECORD_ID      NUMBER
);

-- Comentario para el equipo de DB
COMMENT ON COLUMN GESAP.RECORDATORIO_ENVIO_LOGS.HTTP_METHOD IS 'Método HTTP (GET, POST, etc)';
COMMENT ON COLUMN GESAP.RECORDATORIO_ENVIO_LOGS.USER_AGENT IS 'Navegador/Agente del cliente';
COMMENT ON COLUMN GESAP.RECORDATORIO_ENVIO_LOGS.CORRELATION_ID IS 'ID Único de petición para trazabilidad cruzada Web-API';
COMMENT ON COLUMN GESAP.RECORDATORIO_ENVIO_LOGS.RECORD_ID IS 'ID Real del recordatorio (desencriptado)';
