CREATE TABLE ESTADO_REC_ENVIO_RESPUESTA (
  ID_ESTADO_REC_ENVIO_RESPUESTA NUMBER(12,0) NOT NULL PRIMARY KEY,
  DESCRIPCION VARCHAR2(60)
);

CREATE TABLE RECORDATORIO_ENVIO_RESP (
  ID_RECORDATORIO_ENVIO_RESP NUMBER(12,0) NOT NULL PRIMARY KEY,
  ID_RECORDATORIO_ENVIO NUMBER(12,0),
  FECHA_EMISION DATE,
  FECHA_RESPUESTA_CLIENTE DATE,
  FECHA_TRAMITACION DATE,
  EMPLAZAMIENTO_NOMBRE VARCHAR2(255),
  EMPLAZAMIENTO_DIRECCION VARCHAR2(255),
  TITULAR_NIF VARCHAR2(25),
  TITULAR_RAZON_SOCIAL VARCHAR2(155),
  TITULAR_DIRECCION VARCHAR2(255),
  TITULAR_PERSONA_CONTACTO VARCHAR2(255),
  TITULAR_TELEFONO VARCHAR2(15),
  TITULAR_EMAIL VARCHAR2(155),
  GESTOR_PERSONA_CONTACTO VARCHAR2(255),
  GESTOR_TELEFONO VARCHAR2(15),
  GESTOR_EMAIL VARCHAR2(155),
  GESTOR_NIF VARCHAR2(25),
  GESTOR_RAZON_SOCIAL VARCHAR2(155),
  GESTOR_DIRECCION VARCHAR2(255),
  ID_ESTADO_REC_ENVIO_RESPUESTA NUMBER(12,0),
  MODIFICADO_EMPLAZAMIENTO NUMBER(2,0),
  MODIFICADO_TITULAR NUMBER(2,0),
  MODIFICADO_GESTOR NUMBER(2,0),
  FACTURAR_A VARCHAR2(20),
  FACTURAR_A_OTRO_DESCRIPCION VARCHAR2(255),
  FACTURAR_FORMA_PAGO VARCHAR2(20),
  FACTURAR_CUENTA_BANCO VARCHAR2(34)
);

CREATE TABLE RECORDATORIO_ENVIO_RESP_ITEM (
  ID_RECORDATORIO_ENV_RESP_ITEM NUMBER(12,0) NOT NULL PRIMARY KEY,
  ID_RECORDATORIO_ENVIO_RESP NUMBER(12,0),
  ID_RECORDATORIO_CICLO_ENVIO NUMBER(12,0),
  APROBADO_CLIENTE NUMBER(2,0)
);

CREATE TABLE RECORDATORIO_ENVIO_RESP_NOTA (
  ID_RECORDATORIO_ENV_RESP_NOTA NUMBER(12,0) NOT NULL PRIMARY KEY,
  ID_RECORDATORIO_ENVIO_RESP NUMBER(12,0),
  DESC_RECORDATORIO_ENVIO_NOTA VARCHAR2(255)
);

CREATE TABLE RECORDATORIO_ENVIO (
  ID_RECORDATORIO_ENVIO NUMBER(12,0) NOT NULL PRIMARY KEY,
  ID_EMPLAZAMIENTO NUMBER(12,0),
  ID_TIPO_ACTUACION NUMBER(12,0),
  FECHA_ENVIO_RECORDATORIO DATE,
  TIPO_ENVIO VARCHAR2(10),
  DESTINATARIO VARCHAR2(250),
  CONDICIONES_ECO_CORRECCION VARCHAR2(500),
  EMAIL_DESTINATARIO VARCHAR2(50),
  IDENTIFICADOR_REC_ENVIO VARCHAR2(20),
  ID_CENTRO NUMBER(12,0),
  ES_ECONOMICO NUMBER(2,0),
  CONDICIONES_ECO_GENERALES VARCHAR2(500)
);

CREATE TABLE RECORDATORIO_ENVIO_LOGS (
  LOG_ID NUMBER(19,0) NOT NULL PRIMARY KEY,
  LOG_DATE DATE,
  LOG_LEVEL VARCHAR2(20) NOT NULL,
  LOGGER VARCHAR2(255),
  MESSAGE VARCHAR2(4000),
  EXCEPTION_MSG CLOB,
  STACKTRACE CLOB,
  IP_ADDRESS VARCHAR2(50),
  ENDPOINT VARCHAR2(255),
  USER_NAME VARCHAR2(100),
  SQL_QUERY CLOB,
  HTTP_METHOD VARCHAR2(10),
  USER_AGENT CLOB,
  CORRELATION_ID VARCHAR2(50),
  RECORD_ID NUMBER
);

CREATE TABLE SYS_CONFIGURACION (
  ID_SYS_CONFIGURACION NUMBER(12,0) NOT NULL PRIMARY KEY,
  VERSION VARCHAR2(10),
  ARCHIVO_ACTUALIZACION VARCHAR2(50),
  ES_BBDD_REAL NUMBER(2,0),
  EMAIL_NOTIFICACIONES_DIRECCION VARCHAR2(60),
  EMAIL_NOTIFICACIONES_USUARIO VARCHAR2(60),
  EMAIL_NOTIFICACIONES_PASSWORD VARCHAR2(25),
  SERVIDOR_CORREO_DIRECCION VARCHAR2(60),
  SERVIDOR_CORREO_PUERTO VARCHAR2(6),
  DIRECCION_WEB_VALIDACION_ELEC VARCHAR2(255),
  EMAIL_SSL NUMBER(2,0),
  EMAIL_LOG VARCHAR2(60),
  DOCS_TAMANO_MAXIMO NUMBER(12,0),
  PLAZO_OFERTA_EMITIDA NUMBER(12,0),
  PLAZO_AVISO_LIMITE_AGOTADO NUMBER(12,0),
  PLAZO_REV_CORRECCION_DEFIC NUMBER(12,0),
  DIAS_LIMITE_CIERRE_ACTUACION NUMBER(12,0),
  DIAS_LIMITE_FIRMA_DESDE_CIERRE NUMBER(12,0),
  REFERENCIA_SOLICITUD_VERBAL VARCHAR2(50),
  PROXIMO_NROT_MOVILGMAO NUMBER(12,0),
  FECHA_INICIO_ESTADO_ALARMA DATE,
  FECHA_FIN_ESTADO_ALARMA DATE,
  PLAZO_PLANIF_CORREC_SI_NOTIF NUMBER(12,0),
  REFER_SOLICITUD_VERBAL_VMT VARCHAR2(100),
  TELEFONO_LINEA_900 VARCHAR2(15),
  TIPO_ENTORNO NUMBER(2,0),
  DIAS_LIMITE_ESTADO_INICIAL NUMBER(12,0),
  DIAS_LIMITE_ESTADO_PTE_OFERTA NUMBER(12,0),
  DIAS_LIMITE_ANOTACION_CADUCADA NUMBER(12,0),
  DIAS_LIMITE_DIF_PRIMERAS_INSP NUMBER(12,0),
  DIAS_LIMITE_ENVIO_CLIENTE NUMBER(12,0),
  DIAS_LIMITE_FACTURACION NUMBER(12,0),
  DIAS_LIMITE_NOT_FEHA_RESULT NUMBER(12,0),
  DIAS_LIMITE_FECHA_CANCEL_ANOT NUMBER(12,0),
  EMAIL_ENVIO_GIR VARCHAR2(100),
  DIAS_LIMITE_OFERTA_SIN_SEG NUMBER(12,0),
  SAP_FECHA_INI_BLOQUEO_FAC DATE,
  SAP_FECHA_FIN_BLOQUEO_FAC DATE,
  SAP_FECHA_ALTERNATIVA_FAC DATE,
  PLAZO_MESES_PRECIO_OBSOLETO NUMBER(6,0),
  TERM_COND_GEN_CONTRATACION VARCHAR2(255),
  URL_ACEPTACION_RECORDATORIO VARCHAR2(255)
);


