CREATE TABLE RECORDATORIO_ENVIO (
  ID_RECORDATORIO_ENVIO NUMBER(12,0) NOT NULL PRIMARY KEY,
  ID_EMPLAZAMIENTO NUMBER(12,0),
  ID_TIPO_ACTUACION NUMBER(12,0),
  FECHA_ENVIO_RECORDATORIO DATE,
  TIPO_ENVIO VARCHAR2(10),
  DESTINATARIO VARCHAR2(250),
  CONDICIONES_ECO_CORRECCION VARCHAR2(500),
  EMAIL_DESTINATARIO VARCHAR2(50),
  IDENTIFICADOR_REC_ENVIO VARCHAR2(20),
  ID_CENTRO NUMBER(12,0),
  ES_ECONOMICO NUMBER(2,0),
  CONDICIONES_ECO_GENERALES VARCHAR2(500)
);

CREATE TABLE EMPLAZAMIENTO (
  ID_EMPLAZAMIENTO NUMBER(12,0) NOT NULL PRIMARY KEY,
  ID_APLICACION_EMPRESA NUMBER(12,0),
  ID_CENTRO_GESTOR_ACTUAL NUMBER(12,0),
  ID_TIPO_EMPLAZAMIENTO NUMBER(12,0),
  NOMBRE_EMPLAZAMIENTO VARCHAR2(255),
  ID_TIPO_VIA NUMBER(12,0),
  CALLE VARCHAR2(60),
  NUMERO VARCHAR2(10),
  PORTAL VARCHAR2(10),
  CP VARCHAR2(5),
  POBLACION VARCHAR2(30),
  ID_PROVINCIA NUMBER(12,0),
  ID_PAIS NUMBER(12,0),
  C_MUNICIPIO_INE VARCHAR2(5),
  C_LOCALIDAD_INE VARCHAR2(9),
  C_VIA_DGC VARCHAR2(10),
  ID_CLIENTE_GESTOR NUMBER(12,0),
  ID_CLIENTE_DIRECCION_GESTOR NUMBER(12,0),
  ID_CLIENTE_CONTACTO_GESTOR NUMBER(12,0),
  ES_TITULAR_DATOS_DIRECTOS NUMBER(2,0),
  ID_CLIENTE_TITULAR NUMBER(12,0),
  ID_CLIENTE_DIRECCION_TITULAR NUMBER(12,0),
  ID_CLIENTE_CONTACTO_TITULAR NUMBER(12,0),
  CIF_DNI_TITULAR VARCHAR2(25),
  RAZON_SOCIAL_TITULAR VARCHAR2(60),
  ID_TIPO_VIA_TITULAR NUMBER(12,0),
  CALLE_TITULAR VARCHAR2(60),
  NUMERO_TITULAR VARCHAR2(10),
  PORTAL_TITULAR VARCHAR2(10),
  CP_TITULAR VARCHAR2(5),
  POBLACION_TITULAR VARCHAR2(30),
  ID_PROVINCIA_TITULAR NUMBER(12,0),
  ID_PAIS_TITULAR NUMBER(12,0),
  NOMBRE_TITULAR VARCHAR2(15),
  APELLIDOS_TITULAR VARCHAR2(30),
  TELEFONO_TITULAR VARCHAR2(15),
  FAX_TITULAR VARCHAR2(15),
  EMAIL_TITULAR VARCHAR2(60),
  CARGO_TITULAR VARCHAR2(100),
  FACTURAR_TITULAR NUMBER(2,0),
  NOTIFICAR_FEHACIENTE_TITULAR NUMBER(2,0),
  GM_LATITUD VARCHAR2(20),
  GM_LONGITUD VARCHAR2(20),
  OBSERVACIONES VARCHAR2(255),
  DE_BAJA NUMBER(2,0),
  TMP_TRASPASO NUMBER(12,0)
);

CREATE TABLE TIPO_ACTUACION (
  ID_TIPO_ACTUACION NUMBER(12,0) NOT NULL PRIMARY KEY,
  ID_TIPO_EQUIPO NUMBER(12,0),
  ABREVIATURA_TIPO_ACTUACION VARCHAR2(25),
  DESCRIPCION_TIPO_ACTUACION VARCHAR2(50),
  LISTA_PROVINCIAS_APLICACION VARCHAR2(255),
  COD_TIPO_ACTUACION_GENERICA VARCHAR2(25)
);

CREATE TABLE RECORDATORIO_CICLO_ENVIO (
  ID_RECORDATORIO_CICLO_ENVIO NUMBER(12,0) NOT NULL PRIMARY KEY,
  ID_RECORDATORIO_CICLO NUMBER(12,0),
  SECUENCIA NUMBER(2,0),
  FECHA_ENVIO_RECORDATORIO DATE,
  TIPO_ENVIO VARCHAR2(10),
  DESTINATARIO VARCHAR2(250),
  ID_CLIENTE_GES_ULT NUMBER(12,0),
  ID_CLIENTE_DIRECCION_GES_ULT NUMBER(12,0),
  ID_CLIENTE_CONTACTO_GES_ULT NUMBER(12,0),
  ID_RECORDATORIO_ENVIO NUMBER(12,0),
  PRECIO_ACTUACION_PRIMERA_REV NUMBER(12,2),
  TIEMPO_INSPECCION_PRIMERA_REV NUMBER(12,2),
  TIEMPO_ADICIONAL_PRIMERA_REV NUMBER(12,2),
  OTROS_COSTES NUMBER(12,2)
);

CREATE TABLE RECORDATORIO_CICLO (
  ID_RECORDATORIO_CICLO NUMBER(12,0) NOT NULL PRIMARY KEY,
  ID_EQUIPO_TIPO_ACTUACION NUMBER(12,0),
  ID_SUBTIPO_ACTUACION NUMBER(12,0),
  ID_ESTADO_RECORDATORIO NUMBER(12,0),
  FECHA_PROXIMA_ACTUACION DATE,
  F_PROX_ACT_RECALCULADA NUMBER(2,0),
  FECHA_ENVIO_REC_PRIMERO DATE,
  FECHA_ENVIO_REC_ULTIMO DATE,
  INICIADO_SEGUIMIENTO_CR NUMBER(2,0),
  FECHA_ESTADO_FINAL DATE,
  SECUENCIA_ULTIMA NUMBER(2,0),
  ID_ACTUACION_ASOCIADO NUMBER(12,0)
);

CREATE TABLE EQUIPO_TIPO_ACTUACION (
  ID_EQUIPO_TIPO_ACTUACION NUMBER(12,0) NOT NULL PRIMARY KEY,
  ID_EQUIPO NUMBER(12,0),
  ID_TIPO_ACTUACION NUMBER(12,0),
  CR_ENVIO_TITULAR NUMBER(2,0)
);

CREATE TABLE EQUIPO (
  ID_EQUIPO NUMBER(12,0) NOT NULL PRIMARY KEY,
  ID_EMPLAZAMIENTO NUMBER(12,0),
  ID_TIPO_EQUIPO NUMBER(12,0),
  ID_CENTRO_GESTOR_ACTUAL NUMBER(12,0),
  NOMBRE_EQUIPO VARCHAR2(100),
  IDENTIFICADOR_INDUSTRIA VARCHAR2(50),
  IDENTIFICADOR_PROPIETARIO VARCHAR2(50),
  ID_TIPO_VIA NUMBER(12,0),
  CALLE VARCHAR2(60),
  NUMERO VARCHAR2(10),
  PORTAL VARCHAR2(10),
  C_VIA_DGC VARCHAR2(10),
  COORDENADA_UTMX VARCHAR2(25),
  COORDENADA_UTMY VARCHAR2(25),
  HUSO_UTM NUMBER(12,0),
  NUM_APLICACION_GIR VARCHAR2(10),
  DE_BAJA NUMBER(2,0),
  OBSERVACIONES VARCHAR2(255),
  ZZ_COD_IMPORTACION VARCHAR2(25),
  ZZ_COD_BASE_DATOS VARCHAR2(10),
  ZZ_UUID_ACTIVO_GMAO VARCHAR2(38),
  ID_MOTIVOS_DE_BAJA NUMBER(12,0),
  REF_CATASTRAL VARCHAR2(30)
);

CREATE TABLE SUBTIPO_ACTUACION (
  ID_SUBTIPO_ACTUACION NUMBER(12,0) NOT NULL PRIMARY KEY,
  ID_TIPO_ACTUACION NUMBER(12,0),
  ABREVIATURA_SUBTIPO_ACTUACION VARCHAR2(25),
  DESCRIPCION_SUBTIPO_ACTUACION VARCHAR2(255),
  COD_SUBTIPO_ACTUACION_GENERICA VARCHAR2(25),
  HAY_PERIODICIDAD NUMBER(1,0),
  COD_CATEGORIA VARCHAR2(25),
  DE_BAJA NUMBER(2,0),
  HAY_RECORDATORIO NUMBER(2,0)
);

CREATE TABLE RECORDATORIO_ENVIO_RESP (
  ID_RECORDATORIO_ENVIO_RESP NUMBER(12,0) NOT NULL PRIMARY KEY,
  ID_RECORDATORIO_ENVIO NUMBER(12,0),
  FECHA_EMISION DATE,
  FECHA_RESPUESTA_CLIENTE DATE,
  FECHA_TRAMITACION DATE,
  EMPLAZAMIENTO_NOMBRE VARCHAR2(255),
  EMPLAZAMIENTO_DIRECCION VARCHAR2(255),
  TITULAR_NIF VARCHAR2(25),
  TITULAR_RAZON_SOCIAL VARCHAR2(155),
  TITULAR_DIRECCION VARCHAR2(255),
  TITULAR_PERSONA_CONTACTO VARCHAR2(255),
  TITULAR_TELEFONO VARCHAR2(15),
  TITULAR_EMAIL VARCHAR2(155),
  GESTOR_PERSONA_CONTACTO VARCHAR2(255),
  GESTOR_TELEFONO VARCHAR2(15),
  GESTOR_EMAIL VARCHAR2(155),
  GESTOR_NIF VARCHAR2(25),
  GESTOR_RAZON_SOCIAL VARCHAR2(155),
  GESTOR_DIRECCION VARCHAR2(255),
  ID_ESTADO_REC_ENVIO_RESPUESTA NUMBER(12,0),
  MODIFICADO_EMPLAZAMIENTO NUMBER(2,0),
  MODIFICADO_TITULAR NUMBER(2,0),
  MODIFICADO_GESTOR NUMBER(2,0),
  FACTURAR_A VARCHAR2(20),
  FACTURAR_A_OTRO_DESCRIPCION VARCHAR2(255),
  FACTURAR_FORMA_PAGO VARCHAR2(20),
  FACTURAR_CUENTA_BANCO VARCHAR2(34)
);

CREATE TABLE RECORDATORIO_ENVIO_RESP_ITEM (
  ID_RECORDATORIO_ENV_RESP_ITEM NUMBER(12,0) NOT NULL PRIMARY KEY,
  ID_RECORDATORIO_ENVIO_RESP NUMBER(12,0),
  ID_RECORDATORIO_CICLO_ENVIO NUMBER(12,0),
  APROBADO_CLIENTE NUMBER(2,0)
);


